// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file api/annotations.proto (package otterscale.api, edition 2023)
/* eslint-disable */

import type { GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { MethodOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/annotations.proto.
 */
export const file_api_annotations: GenFile = /*@__PURE__*/
  fileDesc("ChVhcGkvYW5ub3RhdGlvbnMucHJvdG8SDm90dGVyc2NhbGUuYXBpIhcKB0ZlYXR1cmUSDAoEbmFtZRgBIAEoCTpUCgdmZWF0dXJlEh4uZ29vZ2xlLnByb3RvYnVmLk1ldGhvZE9wdGlvbnMY8dvaAyABKAsyFy5vdHRlcnNjYWxlLmFwaS5GZWF0dXJlUgdmZWF0dXJlQipaKGdpdGh1Yi5jb20vb3R0ZXJzY2FsZS9vdHRlcnNjYWxlL2FwaTthcGliCGVkaXRpb25zcOgH", [file_google_protobuf_descriptor]);

/**
 * @generated from message otterscale.api.Feature
 */
export type Feature = Message<"otterscale.api.Feature"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message otterscale.api.Feature.
 * Use `create(FeatureSchema)` to create a new message.
 */
export const FeatureSchema: GenMessage<Feature> = /*@__PURE__*/
  messageDesc(file_api_annotations, 0);

/**
 * @generated from extension: otterscale.api.Feature feature = 7777777;
 */
export const feature: GenExtension<MethodOptions, Feature> = /*@__PURE__*/
  extDesc(file_api_annotations, 0);

