/** Generated from Remote JSON Schema for gateway.networking.k8s.io.v1.BackendTLSPolicy */

/**
 * BackendTLSPolicy provides a way to configure how a Gateway
 * connects to a Backend via TLS.
 */
export interface GatewayNetworkingK8SIoV1BackendTLSPolicy {
  /**
   * ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
   */
  metadata?: {
    /**
     * Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations
     */
    annotations?: {
      [k: string]: string;
    };
    /**
     * Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only.
     */
    deletionGracePeriodSeconds?: number;
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     */
    deletionTimestamp?: string;
    /**
     * GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.
     *
     * If this field is specified and the generated name exists, the server will return a 409.
     *
     * Applied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency
     */
    generateName?: string;
    /**
     * Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the "default" namespace, but "default" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.
     *
     * Must be a DNS_LABEL. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces
     */
    namespace?: string;
    /**
     * An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.
     *
     * Populated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency
     */
    resourceVersion?: string;
    /**
     * Deprecated: selfLink is a legacy read-only field that is no longer populated by the system.
     */
    selfLink?: string;
    /**
     * UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.
     *
     * Populated by the system. Read-only. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
     */
    uid?: string;
    /**
     * A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
     */
    generation?: number;
    /**
     * ManagedFields maps workflow-id and version to the set of fields that are managed by that workflow. This is mostly for internal housekeeping, and users typically shouldn't need to set or understand this field. A workflow can be the user's name, a controller's name, or the name of a specific apply path like "ci-cd". The set of fields is always in the version that the workflow used when modifying the object.
     */
    managedFields?: {
      /**
       * FieldsV1 stores a set of fields in a data structure like a Trie, in JSON format.
       *
       * Each key is either a '.' representing the field itself, and will always map to an empty set, or a string representing a sub-field or item. The string will follow one of these four formats: 'f:<name>', where <name> is the name of a field in a struct, or key in a map 'v:<value>', where <value> is the exact json formatted value of a list item 'i:<index>', where <index> is position of a item in a list 'k:<keys>', where <keys> is a map of  a list item's key fields to their unique values If a key maps to an empty Fields value, the field that key represents is part of the set.
       *
       * The exact format is defined in sigs.k8s.io/structured-merge-diff
       */
      fieldsV1?: {
        [k: string]: unknown;
      };
      /**
       * Manager is an identifier of the workflow managing these fields.
       */
      manager?: string;
      /**
       * Operation is the type of operation which lead to this ManagedFieldsEntry being created. The only valid values for this field are 'Apply' and 'Update'.
       */
      operation?: string;
      /**
       * Subresource is the name of the subresource used to update that object, or empty string if the object was updated through the main resource. The value of this field is used to distinguish between managers, even if they share the same name. For example, a status update will be distinct from a regular update using the same manager name. Note that the APIVersion field is not related to the Subresource field and it always corresponds to the version of the main resource.
       */
      subresource?: string;
      /**
       * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
       */
      time?: string;
      /**
       * APIVersion defines the version of this resource that this field set applies to. The format is "group/version" just like the top-level APIVersion field. It is necessary to track the version of a field set because it cannot be automatically converted.
       */
      apiVersion?: string;
      /**
       * FieldsType is the discriminator for the different fields format and version. There is currently only one possible value: "FieldsV1"
       */
      fieldsType?: string;
      [k: string]: unknown;
    }[];
    /**
     * Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.
     */
    creationTimestamp?: string;
    /**
     * Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list.
     */
    finalizers?: string[];
    /**
     * Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
     */
    labels?: {
      [k: string]: string;
    };
    /**
     * List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller.
     */
    ownerReferences?: {
      /**
       * UID of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#uids
       */
      uid: string;
      /**
       * API version of the referent.
       */
      apiVersion: string;
      /**
       * If true, AND if the owner has the "foregroundDeletion" finalizer, then the owner cannot be deleted from the key-value store until this reference is removed. See https://kubernetes.io/docs/concepts/architecture/garbage-collection/#foreground-deletion for how the garbage collector interacts with this field and enforces the foreground deletion. Defaults to false. To set this field, a user needs "delete" permission of the owner, otherwise 422 (Unprocessable Entity) will be returned.
       */
      blockOwnerDeletion?: boolean;
      /**
       * If true, this reference points to the managing controller.
       */
      controller?: boolean;
      /**
       * Kind of the referent. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
       */
      kind: string;
      /**
       * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
       */
      name: string;
      [k: string]: unknown;
    }[];
    /**
     * Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names#names
     */
    name?: string;
    [k: string]: unknown;
  };
  /**
   * Spec defines the desired state of BackendTLSPolicy.
   */
  spec: {
    /**
     * Options are a list of key/value pairs to enable extended TLS
     * configuration for each implementation. For example, configuring the
     * minimum TLS version or supported cipher suites.
     *
     * A set of common keys MAY be defined by the API in the future. To avoid
     * any ambiguity, implementation-specific definitions MUST use
     * domain-prefixed names, such as `example.com/my-custom-option`.
     * Un-prefixed names are reserved for key names defined by Gateway API.
     *
     * Support: Implementation-specific
     */
    options?: {
      /**
       * AnnotationValue is the value of an annotation in Gateway API. This is used
       * for validation of maps such as TLS options. This roughly matches Kubernetes
       * annotation validation, although the length validation in that case is based
       * on the entire size of the annotations struct.
       */
      [k: string]: string;
    };
    /**
     * TargetRefs identifies an API object to apply the policy to.
     * Only Services have Extended support. Implementations MAY support
     * additional objects, with Implementation Specific support.
     * Note that this config applies to the entire referenced resource
     * by default, but this default may change in the future to provide
     * a more granular application of the policy.
     *
     * TargetRefs must be _distinct_. This means either that:
     *
     * * They select different targets. If this is the case, then targetRef
     *   entries are distinct. In terms of fields, this means that the
     *   multi-part key defined by `group`, `kind`, and `name` must
     *   be unique across all targetRef entries in the BackendTLSPolicy.
     * * They select different sectionNames in the same target.
     *
     * When more than one BackendTLSPolicy selects the same target and
     * sectionName, implementations MUST determine precedence using the
     * following criteria, continuing on ties:
     *
     * * The older policy by creation timestamp takes precedence. For
     *   example, a policy with a creation timestamp of "2021-07-15
     *   01:02:03" MUST be given precedence over a policy with a
     *   creation timestamp of "2021-07-15 01:02:04".
     * * The policy appearing first in alphabetical order by {name}.
     *   For example, a policy named `bar` is given precedence over a
     *   policy named `baz`.
     *
     * For any BackendTLSPolicy that does not take precedence, the
     * implementation MUST ensure the `Accepted` Condition is set to
     * `status: False`, with Reason `Conflicted`.
     *
     * Implementations SHOULD NOT support more than one targetRef at this
     * time. Although the API technically allows for this, the current guidance
     * for conflict resolution and status handling is lacking. Until that can be
     * clarified in a future release, the safest approach is to support a single
     * targetRef.
     *
     * Support: Extended for Kubernetes Service
     *
     * Support: Implementation-specific for any other resource
     *
     * @minItems 1
     * @maxItems 16
     */
    targetRefs: {
      /**
       * Group is the group of the target resource.
       */
      group: string;
      /**
       * Kind is kind of the target resource.
       */
      kind: string;
      /**
       * Name is the name of the target resource.
       */
      name: string;
      /**
       * SectionName is the name of a section within the target resource. When
       * unspecified, this targetRef targets the entire resource. In the following
       * resources, SectionName is interpreted as the following:
       *
       * * Gateway: Listener name
       * * HTTPRoute: HTTPRouteRule name
       * * Service: Port name
       *
       * If a SectionName is specified, but does not exist on the targeted object,
       * the Policy must fail to attach, and the policy implementation should record
       * a `ResolvedRefs` or similar Condition in the Policy's status.
       */
      sectionName?: string;
      [k: string]: unknown;
    }[];
    /**
     * Validation contains backend TLS validation configuration.
     */
    validation: {
      /**
       * WellKnownCACertificates specifies whether system CA certificates may be used in
       * the TLS handshake between the gateway and backend pod.
       *
       * If WellKnownCACertificates is unspecified or empty (""), then CACertificateRefs
       * must be specified with at least one entry for a valid configuration. Only one of
       * CACertificateRefs or WellKnownCACertificates may be specified, not both.
       * If an implementation does not support the WellKnownCACertificates field, or
       * the supplied value is not recognized, the implementation MUST ensure the
       * `Accepted` Condition on the BackendTLSPolicy is set to `status: False`, with
       * a Reason `Invalid`.
       *
       * Support: Implementation-specific
       */
      wellKnownCACertificates?: 'System';
      /**
       * CACertificateRefs contains one or more references to Kubernetes objects that
       * contain a PEM-encoded TLS CA certificate bundle, which is used to
       * validate a TLS handshake between the Gateway and backend Pod.
       *
       * If CACertificateRefs is empty or unspecified, then WellKnownCACertificates must be
       * specified. Only one of CACertificateRefs or WellKnownCACertificates may be specified,
       * not both. If CACertificateRefs is empty or unspecified, the configuration for
       * WellKnownCACertificates MUST be honored instead if supported by the implementation.
       *
       * A CACertificateRef is invalid if:
       *
       * * It refers to a resource that cannot be resolved (e.g., the referenced resource
       *   does not exist) or is misconfigured (e.g., a ConfigMap does not contain a key
       *   named `ca.crt`). In this case, the Reason must be set to `InvalidCACertificateRef`
       *   and the Message of the Condition must indicate which reference is invalid and why.
       *
       * * It refers to an unknown or unsupported kind of resource. In this case, the Reason
       *   must be set to `InvalidKind` and the Message of the Condition must explain which
       *   kind of resource is unknown or unsupported.
       *
       * * It refers to a resource in another namespace. This may change in future
       *   spec updates.
       *
       * Implementations MAY choose to perform further validation of the certificate
       * content (e.g., checking expiry or enforcing specific formats). In such cases,
       * an implementation-specific Reason and Message must be set for the invalid reference.
       *
       * In all cases, the implementation MUST ensure the `ResolvedRefs` Condition on
       * the BackendTLSPolicy is set to `status: False`, with a Reason and Message
       * that indicate the cause of the error. Connections using an invalid
       * CACertificateRef MUST fail, and the client MUST receive an HTTP 5xx error
       * response. If ALL CACertificateRefs are invalid, the implementation MUST also
       * ensure the `Accepted` Condition on the BackendTLSPolicy is set to
       * `status: False`, with a Reason `NoValidCACertificate`.
       *
       * A single CACertificateRef to a Kubernetes ConfigMap kind has "Core" support.
       * Implementations MAY choose to support attaching multiple certificates to
       * a backend, but this behavior is implementation-specific.
       *
       * Support: Core - An optional single reference to a Kubernetes ConfigMap,
       * with the CA certificate in a key named `ca.crt`.
       *
       * Support: Implementation-specific - More than one reference, other kinds
       * of resources, or a single reference that includes multiple certificates.
       *
       * @maxItems 8
       */
      caCertificateRefs?: {
        /**
         * Group is the group of the referent. For example, "gateway.networking.k8s.io".
         * When unspecified or empty string, core API group is inferred.
         */
        group: string;
        /**
         * Kind is kind of the referent. For example "HTTPRoute" or "Service".
         */
        kind: string;
        /**
         * Name is the name of the referent.
         */
        name: string;
        [k: string]: unknown;
      }[];
      /**
       * Hostname is used for two purposes in the connection between Gateways and
       * backends:
       *
       * 1. Hostname MUST be used as the SNI to connect to the backend (RFC 6066).
       * 2. Hostname MUST be used for authentication and MUST match the certificate
       *    served by the matching backend, unless SubjectAltNames is specified.
       * 3. If SubjectAltNames are specified, Hostname can be used for certificate selection
       *    but MUST NOT be used for authentication. If you want to use the value
       *    of the Hostname field for authentication, you MUST add it to the SubjectAltNames list.
       *
       * Support: Core
       */
      hostname: string;
      /**
       * SubjectAltNames contains one or more Subject Alternative Names.
       * When specified the certificate served from the backend MUST
       * have at least one Subject Alternate Name matching one of the specified SubjectAltNames.
       *
       * Support: Extended
       *
       * @maxItems 5
       */
      subjectAltNames?: {
        /**
         * Hostname contains Subject Alternative Name specified in DNS name format.
         * Required when Type is set to Hostname, ignored otherwise.
         *
         * Support: Core
         */
        hostname?: string;
        /**
         * Type determines the format of the Subject Alternative Name. Always required.
         *
         * Support: Core
         */
        type: 'Hostname' | 'URI';
        /**
         * URI contains Subject Alternative Name specified in a full URI format.
         * It MUST include both a scheme (e.g., "http" or "ftp") and a scheme-specific-part.
         * Common values include SPIFFE IDs like "spiffe://mycluster.example.com/ns/myns/sa/svc1sa".
         * Required when Type is set to URI, ignored otherwise.
         *
         * Support: Core
         */
        uri?: string;
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Status defines the current state of BackendTLSPolicy.
   */
  status?: {
    /**
     * Ancestors is a list of ancestor resources (usually Gateways) that are
     * associated with the policy, and the status of the policy with respect to
     * each ancestor. When this policy attaches to a parent, the controller that
     * manages the parent and the ancestors MUST add an entry to this list when
     * the controller first sees the policy and SHOULD update the entry as
     * appropriate when the relevant ancestor is modified.
     *
     * Note that choosing the relevant ancestor is left to the Policy designers;
     * an important part of Policy design is designing the right object level at
     * which to namespace this status.
     *
     * Note also that implementations MUST ONLY populate ancestor status for
     * the Ancestor resources they are responsible for. Implementations MUST
     * use the ControllerName field to uniquely identify the entries in this list
     * that they are responsible for.
     *
     * Note that to achieve this, the list of PolicyAncestorStatus structs
     * MUST be treated as a map with a composite key, made up of the AncestorRef
     * and ControllerName fields combined.
     *
     * A maximum of 16 ancestors will be represented in this list. An empty list
     * means the Policy is not relevant for any ancestors.
     *
     * If this slice is full, implementations MUST NOT add further entries.
     * Instead they MUST consider the policy unimplementable and signal that
     * on any related resources such as the ancestor that would be referenced
     * here. For example, if this list was full on BackendTLSPolicy, no
     * additional Gateways would be able to reference the Service targeted by
     * the BackendTLSPolicy.
     *
     * @maxItems 16
     */
    ancestors: {
      /**
       * ControllerName is a domain/path string that indicates the name of the
       * controller that wrote this status. This corresponds with the
       * controllerName field on GatewayClass.
       *
       * Example: "example.net/gateway-controller".
       *
       * The format of this field is DOMAIN "/" PATH, where DOMAIN and PATH are
       * valid Kubernetes names
       * (https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).
       *
       * Controllers MUST populate this field when writing status. Controllers should ensure that
       * entries to status populated with their ControllerName are cleaned up when they are no
       * longer necessary.
       */
      controllerName: string;
      /**
       * AncestorRef corresponds with a ParentRef in the spec that this
       * PolicyAncestorStatus struct describes the status of.
       */
      ancestorRef: {
        /**
         * Group is the group of the referent.
         * When unspecified, "gateway.networking.k8s.io" is inferred.
         * To set the core API group (such as for a "Service" kind referent),
         * Group must be explicitly set to "" (empty string).
         *
         * Support: Core
         */
        group?: string;
        /**
         * Kind is kind of the referent.
         *
         * There are two kinds of parent resources with "Core" support:
         *
         * * Gateway (Gateway conformance profile)
         * * Service (Mesh conformance profile, ClusterIP Services only)
         *
         * Support for other resources is Implementation-Specific.
         */
        kind?: string;
        /**
         * Name is the name of the referent.
         *
         * Support: Core
         */
        name: string;
        /**
         * Namespace is the namespace of the referent. When unspecified, this refers
         * to the local namespace of the Route.
         *
         * Note that there are specific rules for ParentRefs which cross namespace
         * boundaries. Cross-namespace references are only valid if they are explicitly
         * allowed by something in the namespace they are referring to. For example:
         * Gateway has the AllowedRoutes field, and ReferenceGrant provides a
         * generic way to enable any other kind of cross-namespace reference.
         *
         * Support: Core
         */
        namespace?: string;
        /**
         * Port is the network port this Route targets. It can be interpreted
         * differently based on the type of parent resource.
         *
         * When the parent resource is a Gateway, this targets all listeners
         * listening on the specified port that also support this kind of Route(and
         * select this Route). It's not recommended to set `Port` unless the
         * networking behaviors specified in a Route must apply to a specific port
         * as opposed to a listener(s) whose port(s) may be changed. When both Port
         * and SectionName are specified, the name and port of the selected listener
         * must match both specified values.
         *
         * Implementations MAY choose to support other parent resources.
         * Implementations supporting other types of parent resources MUST clearly
         * document how/if Port is interpreted.
         *
         * For the purpose of status, an attachment is considered successful as
         * long as the parent resource accepts it partially. For example, Gateway
         * listeners can restrict which Routes can attach to them by Route kind,
         * namespace, or hostname. If 1 of 2 Gateway listeners accept attachment
         * from the referencing Route, the Route MUST be considered successfully
         * attached. If no Gateway listeners accept attachment from this Route,
         * the Route MUST be considered detached from the Gateway.
         *
         * Support: Extended
         */
        port?: number;
        /**
         * SectionName is the name of a section within the target resource. In the
         * following resources, SectionName is interpreted as the following:
         *
         * * Gateway: Listener name. When both Port (experimental) and SectionName
         * are specified, the name and port of the selected listener must match
         * both specified values.
         * * Service: Port name. When both Port (experimental) and SectionName
         * are specified, the name and port of the selected listener must match
         * both specified values.
         *
         * Implementations MAY choose to support attaching Routes to other resources.
         * If that is the case, they MUST clearly document how SectionName is
         * interpreted.
         *
         * When unspecified (empty string), this will reference the entire resource.
         * For the purpose of status, an attachment is considered successful if at
         * least one section in the parent resource accepts it. For example, Gateway
         * listeners can restrict which Routes can attach to them by Route kind,
         * namespace, or hostname. If 1 of 2 Gateway listeners accept attachment from
         * the referencing Route, the Route MUST be considered successfully
         * attached. If no Gateway listeners accept attachment from this Route, the
         * Route MUST be considered detached from the Gateway.
         *
         * Support: Core
         */
        sectionName?: string;
        [k: string]: unknown;
      };
      /**
       * Conditions describes the status of the Policy with respect to the given Ancestor.
       *
       * @minItems 1
       * @maxItems 8
       */
      conditions: {
        /**
         * type of condition in CamelCase or in foo.example.com/CamelCase.
         */
        type: string;
        /**
         * lastTransitionTime is the last time the condition transitioned from one status to another.
         * This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
         */
        lastTransitionTime: string;
        /**
         * message is a human readable message indicating details about the transition.
         * This may be an empty string.
         */
        message: string;
        /**
         * observedGeneration represents the .metadata.generation that the condition was set based upon.
         * For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
         * with respect to the current state of the instance.
         */
        observedGeneration?: number;
        /**
         * reason contains a programmatic identifier indicating the reason for the condition's last transition.
         * Producers of specific condition types may define expected values and meanings for this field,
         * and whether the values are considered a guaranteed API.
         * The value should be a CamelCase string.
         * This field may not be empty.
         */
        reason: string;
        /**
         * status of the condition, one of True, False, Unknown.
         */
        status: 'True' | 'False' | 'Unknown';
        [k: string]: unknown;
      }[];
      [k: string]: unknown;
    }[];
    [k: string]: unknown;
  };
  /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   */
  apiVersion?: string;
  /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   */
  kind?: string;
  [k: string]: unknown;
}
